name: Build
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build-codeedit-cli:
    name: Building CodeEdit CLI
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Building
        run: swift build -c release --arch arm64 --arch x86_64
