name: CI - Deploy
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
jobs:
  swiftlint:
    name: SwiftLint
    uses: ./.github/workflows/swiftlint.yml
    secrets: inherit
  test:
    name: Build CodeEdit CLI
    needs: swiftlint
    uses: ./.github/workflows/build.yml
    secrets: inherit
  deploy:
    name: Deploy CodeEdit CLI
    needs: [swiftlint, test]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
