name: CI - Push to main
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  swiftlint:
    name: SwiftLint
    uses: ./.github/workflows/swiftlint.yml
    secrets: inherit
  test:
    name: Build CodeEdit CLI
    needs: swiftlint
    uses: ./.github/workflows/build.yml
    secrets: inherit
